<a href="https://colab.research.google.com/github/sruthijasti/FML-Lab/blob/main/Exp-7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **KNN**

---



**Diabetes Prediction Classifier using Logistic KNN**

In [1]:
#import the packages

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [2]:
#Importing the dataset
data=pd.read_csv("https://assets.datacamp.com/production/repositories/628/datasets/444cdbf175d5fbf564b564bd36ac21740627a834/diabetes.csv")

In [3]:
data.head()

pregnancies  glucose  diastolic  triceps  insulin   bmi    dpf  age  \
0            6      148         72       35        0  33.6  0.627   50   
1            1       85         66       29        0  26.6  0.351   31   
2            8      183         64        0        0  23.3  0.672   32   
3            1       89         66       23       94  28.1  0.167   21   
4            0      137         40       35      168  43.1  2.288   33   

   diabetes  
0         1  
1         0  
2         1  
3         0  
4         1

In [4]:
#Removing the label from the input data
X = data.drop('diabetes', axis=1).values
y = data['diabetes'].values

**Splitting of the data:**

In [5]:
#Splitting the data set into training and testing records
X_train, X_test, y_train, y_test =train_test_split(X, y, test_size=0.1, random_state=41)


**Scale Data:**

Standardization is the process of transforming data in a way such that the mean of each column becomes equal to zero, and the standard deviation of each column is one. This way, you obtain the same scale for all columns. 

In [6]:
X_train[0], np.mean(X_train[0]), np.std(X_train[0])

(array([ 1.   , 99.   , 72.   , 30.   , 18.   , 38.6  ,  0.412, 21.   ]),
 35.0015,
 32.288329404755515)

In [7]:
#scaling the columns
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)

In [8]:
X_train[0], np.mean(X_train[0]), np.std(X_train[0])

(array([-0.8497724 , -0.68806035,  0.11286109,  0.59957466, -0.51975652,
         0.8342348 , -0.18874889, -1.0565332 ]),
 -0.2195251008414878,
 0.6422830875185573)

In [9]:
#creating a model and training it by fitting number of neighbors
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)

KNeighborsClassifier()

In [10]:
#evaluate the model
X_test = scaler.transform(X_test)
y_pred = knn.predict(X_test)

**Performance of training data:**

In [11]:
knn.score(X_train, y_train)

0.8234442836468886

**Performance of testing data:**

In [12]:
knn.score(X_test, y_test)

0.8051948051948052

***Confusion Matrix:***

In [13]:
confusion_matrix(y_test, y_pred)

array([[46,  6],
       [ 9, 16]])

***Evaluation metrics of logistic regression***

In [14]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.84      0.88      0.86        52
           1       0.73      0.64      0.68        25

    accuracy                           0.81        77
   macro avg       0.78      0.76      0.77        77
weighted avg       0.80      0.81      0.80        77



**Conclusion:**Our classification model performed well upto a certain extent.